@baseUrl = http://localhost:3333

# @name create_person
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "apelido" : "josé",
  "nome" : "José Roberto",
  "nascimento" : "2000-10-01",
  "stack" : ["C#", "Node", "Oracle"]
}

###

# @name get_person
GET {{baseUrl}}/pessoas/579c5c91-a8ef-401e-9f3c-020b3a73d52a
Content-Type: application/json
